// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANMxZq0pDASufD9FOOYTBXhiVJ_ActEH0',
    appId: '1:447127179929:web:5823ba09e71a843c22de08',
    messagingSenderId: '447127179929',
    projectId: 'pet-emergency-567b9',
    authDomain: 'pet-emergency-567b9.firebaseapp.com',
    storageBucket: 'pet-emergency-567b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNgObxJFLKxs7jK2lDzz__5Iw4N5DJ0c',
    appId: '1:447127179929:android:9d0ba0baa6a32fab22de08',
    messagingSenderId: '447127179929',
    projectId: 'pet-emergency-567b9',
    storageBucket: 'pet-emergency-567b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEplCyFT02KRdJPbnJY-dfipga8MjbzXE',
    appId: '1:447127179929:ios:5dd9d3c158ccee1e22de08',
    messagingSenderId: '447127179929',
    projectId: 'pet-emergency-567b9',
    storageBucket: 'pet-emergency-567b9.firebasestorage.app',
    iosBundleId: 'com.example.petemergency',
  );
}
